GPT Chat component, navbar component and modal component
Venture-Miner/wagademy pull request #52
Opened 2024-02-29 15:58 UTC by ClaraFelix

2024-03-01 13:18 UTC, dev-luizf reviewed
I couldn't enter the route of the gpt chat page.

2024-03-06 22:45 UTC, Bidfca requested changes
![image](https://github.com/Venture-Miner/wagademy/assets/60355496/3b500566-d070-476f-b6ab-3b70fbeaf366)
In certain screen sizes, the options don't have a margin between them and the page border. Also, when the options are vertical, they get too close to each other. Moreover, when I hover over the options, the text jumps around too much.

2024-03-06 23:47 UTC, Bidfca requested changes
![image](https://github.com/Venture-Miner/wagademy/assets/60355496/2f162213-29cd-46b2-94b4-557427f26fcd)
The text in the chat has low contrast with the background. Additionally, I had to scroll to see the text area to send the message, even though there wasn't enough chat history to fill the screen. I was very confused by this because I was not able to find it at first.
![image](https://github.com/Venture-Miner/wagademy/assets/60355496/485da167-0f05-4246-9c2e-59cd549598c3)

2024-03-07 23:31 UTC, Bidfca approved these changes

2024-03-07 23:32 UTC, merged