2.0.2 show more jobs | Physical Person and 2.0.3 Jobs details | Physical Person
Venture-Miner/wagademy pull request #61
Opened 2024-03-12 15:23 UTC by ClaraFelix

2024-03-13 18:20 UTC, dev-luizf requested changes

2024-03-13 18:20 UTC, dev-luizf commented on apps/frontend/src/app/pages/jobs-details/jobs-details.component.html
> +          <p class="font-mono text-base-200">{{ locale }}</p>
><p class="font-mono text-base-200">{{ locale }}</p>
should be allocation

2024-03-13 18:20 UTC, dev-luizf commented on apps/frontend/src/app/pages/jobs-details/jobs-details.component.html
> +          {{ name }}
>{{ name }}

should be title

2024-03-13 18:20 UTC, dev-luizf commented on apps/frontend/src/app/pages/jobs-details/jobs-details.component.html
> +        <p class="font-mono text-base-200">{{ responsibilities }}</p>
Responsabilities and description should be the same element. We won't divide it in different things, it is all description.

2024-03-13 18:20 UTC, dev-luizf commented on apps/frontend/src/app/pages/jobs-details/jobs-details.component.html
> +          <img
The image and the company name are too close:

![Captura de tela de 2024-03-13 15-13-37](https://github.com/Venture-Miner/wagademy/assets/83927877/742efc63-7d48-4060-adba-efcf346c4f6d)

2024-03-13 18:20 UTC, dev-luizf commented on apps/frontend/src/app/pages/jobs/jobs.component.html
1. Cards cursor should be pointer.
2. The card description should have a overflow with "..." and not cut off halfway through the last line.
![Captura de tela de 2024-03-13 15-01-28](https://github.com/Venture-Miner/wagademy/assets/83927877/369c8c09-8bff-42c0-a85d-5a998701392b)

3. The search is not working.
![Captura de tela de 2024-03-13 15-18-53](https://github.com/Venture-Miner/wagademy/assets/83927877/0fba1005-364c-43b4-b584-8f6f809f46ee)

4. The "all" filter should be selected by default when the user enters the page.
![Captura de tela de 2024-03-13 15-19-23](https://github.com/Venture-Miner/wagademy/assets/83927877/11ab6d7b-bd86-4c9e-a314-1d3238a5ae0b)

2024-03-21 19:07 UTC, Bidfca requested changes

2024-03-21 19:30 UTC, Bidfca commented on apps/frontend/src/app/shared/components/cards/cards.component.html
> +        <p class="text-base-200 font-mono h-24 overflow-hidden line-clamp-3">
Remember to apply these changes in https://github.com/Venture-Miner/wagademy/pull/63 too

2024-03-21 22:56 UTC, ClaraFelix commented on apps/frontend/src/app/pages/jobs-details/jobs-details.component.html
> +          <p class="font-mono text-base-200">{{ jobType }}</p>
Bia, I couldn't identify the font problem. Is it no longer working?

![image](https://github.com/Venture-Miner/wagademy/assets/80846078/8f0ce37a-873b-4153-9fbc-ee2f6d93e897)
![image](https://github.com/Venture-Miner/wagademy/assets/80846078/423a4ec0-37c6-4339-a878-0922c5514d5a)

2024-03-22 19:44 UTC, merged