2.0.1 GPTs | Physical Person e modal (frontend)
Venture-Miner/wagademy pull request #63
Opened 2024-03-13 21:57 UTC by ClaraFelix

2024-03-14 10:53 UTC, dev-luizf requested changes
1. Cards cursor should be pointer.

2. The search is not working.

3. The "all" filter should be selected by default when the user enters the page.
![Captura de tela de 2024-03-13 15-19-23](https://github.com/Venture-Miner/wagademy/assets/83927877/11ab6d7b-bd86-4c9e-a314-1d3238a5ae0b)

2024-03-19 11:13 UTC, dev-luizf approved these changes

2024-03-21 19:26 UTC, Bidfca requested changes

2024-03-21 19:26 UTC, Bidfca commented on apps/frontend/src/app/pages/person/gpt-list/gpt-list.component.html
> +<div class="container mx-auto min-h-screen px-3 sm:px-0">
![image](https://github.com/Venture-Miner/wagademy/assets/60355496/2508a5e3-7c95-4b7d-b581-2d72513ef5dc)

2024-03-22 18:32 UTC, merged