Add guard to routes, Auth guard and account type guard
Venture-Miner/wagademy pull request #75
Opened 2024-04-05 18:06 UTC by EduardoABG

2024-04-07 17:36 UTC, Bidfca requested changes

2024-04-07 17:36 UTC, Bidfca commented on apps/frontend/src/app/pages/person/job-applications-all/job-applications-all.component.html
> +  } @if(jobApplications.all.length&&applicationsType === 'all'){
is this correct? there's no space around &&

2024-04-07 17:36 UTC, Bidfca commented on apps/frontend/src/app/pages/person/job-applications-all/job-applications-all.component.html
> +  } @if(jobApplications.interviewInvites.length&&applicationsType ===
is this correct? there's no space around &&

2024-04-12 17:26 UTC, dev-luizf approved these changes

2024-04-12 17:26 UTC, merged