Loading component
Venture-Miner/wagademy pull request #99
Opened 2024-04-26 17:42 UTC by ClaraFelix

2024-04-29 12:14 UTC, dev-luizf commented on apps/frontend/src/app/pages/jobs/jobs.component.html
This loading component isn't being displayed. Also, you don't need all of these conditions, you just need to check @if(isLoading) and@if(!jobs.length) and remove the other ones

2024-05-02 10:41 UTC, dev-luizf requested changes
Currently, the loading is infinite on the person pages, and additionally, on the job page, it is appearing along with the message 'there is no content'.

![Captura de tela de 2024-05-02 07-37-03](https://github.com/Venture-Miner/wagademy/assets/83927877/d76f3444-f40c-4112-bf55-bba9bf9ea3ab)

Another detail is that the background of the component is slightly darker than the rest of the page. I believe it should be white.

2024-05-03 19:01 UTC, ClaraFelix commented
It's infinite on pages that don't have integration yet, that's why I just called loading

2024-05-03 19:37 UTC, ClaraFelix commented
Done :)

2024-05-15 18:54 UTC, merged